// in javaScript <li></li> this is known as """"" element"""""...any thing which we called an element is always be in < > these bracket.....
//and anything written in these elements are known as """""text node"""""...

//# question spot element and text node????
// <span> JavaScript </span>
//? span is element and JavaScript is text node....